### ISSUE TITLE
Inquiry Title to "Type" + "Company" 

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#10]

**Comment by adamsfallen** [comment]
Unsure what you mean - Can you be more specific here?

**Comment by alexpelletier** [comment]
You asked for how we could be more specific with the Inquiry title- see screen shot.
Instead of "Symanet" which is company name, change to the type of inquiry (Researcher/scientist, lab, other) + Symanet.  (separately, we currently have no way to determine what type of inquiry- will they all be generic..etc...)
<img width="472" alt="screen shot 2016-02-16 at 10 16 39 am" src="https://cloud.githubusercontent.com/assets/14278320/13080266/e7fd6eb4-d495-11e5-85cf-d524d53210ad.png">

**Comment by adamsfallen** [comment]
The former issue is roughly supported and for the latter we can add a hidden field for source that labels the type of inquiry as you describe, which will be helpful for backend tracking. I'll create a new issue.
