### ISSUE TITLE
Other Question Form changes

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#14]
1. Please change "Market" to "Lab"
2. Please change "description of Inquiry" to "Ask your Question"

**Comment by alexpelletier** [comment]
on hold- team deciding if "Other questions" still a form they want to keep.

**Comment by lukad03** [comment]
@adamsfallen all you https://github.com/presidential-innovation-fellows/ceic-partnering/pull/43
