### ISSUE TITLE
 Submit a Form- confirmation page + conditional

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#15]
Please create a confirmation page with language <placeholder for now until I confirm with business users>:
"Thank you for your inquiry. The Clean Energy Investment Center at the Department of Energy together with the Labs will respond to you as soon as possible."

---

Remember:
Request from business users to have a conditional response based on what capability/industry- so if one selected and not currently handled, message 1 will appear. If selected is supported, message 2 will appear.

**Comment by adamsfallen** [comment]
Accepted - Luke and I will discuss the best way to manage this.

**Comment by alexpelletier** [comment]
If Inquiry= Connect with an Expert, then "Thank you for your interest. Your inquiry has been received and you will be contacted soon." <I am confirming what they want as they also want to include a link to a doc in confirmation email>

If Partner with a lab: "Thank you for your interest. Your inquiry has been received and you will be contacted soon." <to confirm: if you are interested in earning more about partnering with the Labs, check out this report." (they will share a link to lab report on OTT website)>

They also want to have an email confirmation go to the inquiry requestor with the same language (but not the link to doc part).

**Comment by lukad03** [comment]
create conf page
