### ISSUE TITLE
Nutshell- Leads table columns

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#16]
What columns can change? e.g. would like "Industry" or "Capability" column
<img width="1074" alt="screen shot 2016-02-16 at 10 01 34 am" src="https://cloud.githubusercontent.com/assets/14278320/13079779/d9b288c8-d493-11e5-8be2-8af43b949a61.png">

**Comment by adamsfallen** [comment]
These are unique to each user, so within your account if you click "columns" you can add or delete as many as you'd like. For now, "Assignee", "Milestone", "Industry" and "Status" are most obviously useful / supported but we can add support for more as we go.
