### ISSUE TITLE
"Connect with an Expert" form

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#21]
1. Change "Company" to "Organization"
2. Include "Industry" drop down (refer to issue to be logged on two level drop down list) change to "Technology Area of Interest"
3. Instead of free text box title name, change to "Question for an Expert"
4. Make contact info required

**Comment by alexpelletier** [comment]
Luke- there was a question about the ordering of the fields and whether the contact info should come after the "Teach Area of Interest" and "Question to Expert" instead of at the top.

**Comment by alexpelletier** [comment]
refer to issue #22 for drop down list

**Comment by lukad03** [comment]
@adamsfallen all you https://github.com/presidential-innovation-fellows/ceic-partnering/pull/42
