### ISSUE TITLE
Technology Area of Inquiry list

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#22]
![image](https://cloud.githubusercontent.com/assets/14278320/13091322/8ca414ae-d4c8-11e5-82e7-b7d8e3fbd0da.png)

**Comment by alexpelletier** [comment]
Another issue will be opened to tie these to labs

**Comment by adamsfallen** [comment]
@lukad03 said he could support hierarchical headers with some custom drop-downs - updating just the items themselves to Partnering form for now and then reassigning to Luke to implement custom drop-downs.
