### ISSUE TITLE
Partner with a Lab

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#23]
1. Description:
   If you want to partner with a lab or better understand capabilities let us know what you are looking to explore"
2. Make First/Last/email required 
3. Change "Company" to "Organization"
4. Change "Industry" to "National Laboratory" (they will send the list of 17) as a drop down
5. Add a new field "What is your objective in connecting with this lab?"
         options: 
          - Licensing Intellectual Property
          - Accessing User Facilities
          - Exploring Partnering Mechanisms
          - Learning more about the Lab
6. Description of interest free text box change to "Provide additional detail here"

**Comment by alexpelletier** [comment]
List of 17 labs:
Ames Laboratory
Argonne National Laboratory
Brookhaven National Laboratory
Fermi National Accelerator Laboratory
Idaho National Laboratory
Lawrence Berkeley National Laboratory
Lawrence Livermore National Laboratory
Los Alamos National Laboratory
National Energy Technology Laboratory
National Renewable Energy Laboratory
Oak Ridge National Laboratory
Pacific Northwest National Laboratory
Princeton Plasma Physics Laboratory
Sandia National Laboratories
Savannah River National Laboratory
SLAC National Accelerator Laboratory

**Comment by lukad03** [comment]
@alexpelletier The final text box doesn't make much sense. Let's keep the "objective connecting with this lab" input and not ask for the other.

**Comment by lukad03** [comment]
@adamsfallen https://github.com/presidential-innovation-fellows/ceic-partnering/pull/41

**Comment by lukad03** [comment]
Punting on "Objective" input in the interest of time - creating a separate issue for it.
