### ISSUE TITLE
Auto email to requestor

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#29]
Send auto reply to the email of requestor:
Subject: CEIC Partnering Service request
Text: Thank you for your interest. Your inquiry has been received and you will be contacted soon.

**Comment by alexpelletier** [comment]
add to 'your inquiry' on <date/time>

**Comment by adamsfallen** [comment]
This is now supported

![image](https://cloud.githubusercontent.com/assets/220957/13125548/1db2a57a-d594-11e5-82f2-a47858be7b38.png)

**Comment by adamsfallen** [comment]
@alexpelletier actually before I close this please provide feedback to let me know if this is what you were looking for!

**Comment by alexpelletier** [comment]
Just checking - tried the "Connect with Expert" and got "speak to a scientist"- can we change this?
<img width="811" alt="screen shot 2016-02-22 at 7 24 24 pm" src="https://cloud.githubusercontent.com/assets/14278320/13237354/6da6a33e-d999-11e5-9d66-81dcbf536903.png">

**Comment by alexpelletier** [comment]
also, I will confirm the language with CEIC. (any way it can have another auto reply email besides wufoo?)

**Comment by alexpelletier** [comment]
Also- "Partner with a lab" has additional detail in the email: I will confirm it is needed and should also be included in "Connect with Expert"
<img width="812" alt="screen shot 2016-02-22 at 7 52 40 pm" src="https://cloud.githubusercontent.com/assets/14278320/13237911/5da79304-d99d-11e5-8986-c35b0c7c33b0.png">

**Comment by adamsfallen** [comment]
1. Sure we can rename the subjects to whatever - those just happen to be what the forms are called in Wufoo.
2. We can include the form entry "additional details" or not at your preference , but would have to include all/none, including hidden fields.
3. We just use wufoo as the auto-email service. We can set the reply-to as whatever but the mail server is whatever it is, right?

**Comment by alexpelletier** [comment]
1. Please change "Speak with a Scientist" to "Connect with an Expert" in wufoo form (will create another issue for this)
2. No additional details- but note, the text may change based on business feedback.
3. So the mail server at launch will be wufoo? or will it have a .gov there? (wufoo is a silly name...and doesn't look legit).
