### ISSUE TITLE
Add Objective Input to Partner Form

### ISSUE THREAD

**Issue by lukad03** [presidential-innovation-fellows/ceic-partnering#44]
Punted on this in the interest of time.
- Add a new field "What is your objective in connecting with this lab?" options: - Licensing Intellectual Property - Accessing User Facilities - Exploring Partnering Mechanisms - Learning more about the Lab

https://github.com/presidential-innovation-fellows/ceic-partnering/issues/23

**Comment by adamsfallen** [comment]
@alexpelletier let me know where you want this data to end up and what its functional purpose should be - in the meantime it's just not being included in this release.

**Comment by alexpelletier** [comment]
related to #31 title in nutshell of "Lead" should have type (e.g. Technical expert or Partner) and also categorization (Tech expert= tech area of interest, Partner=Objective).

**Comment by adamsfallen** [comment]
FYI @alexpelletier your comment above is different from either #31 or #44 and so it belongs in a new feature request.

**Comment by adamsfallen** [comment]
@alexpelletier - #31 is about adding this data as tags not as part of the "Lead title."

FYI putting data as part of "Lead title" (at least exclusively), prevents us from doing real analytics on it (don't know if that's part of the functional purpose of the question - still need clarification there).

**Comment by alexpelletier** [comment]
Sorry- for clarification, this is about adding this to the Tags. We need:
1. the ability to clarify Lead type from what was sent on the inquiry
2. the ability to do analytics in reports (# of leads, by type)

**Comment by adamsfallen** [comment]
Okay in that case it might make the most sense as its own custom field, depending on how the inquiry stuff shakes out, if that sounds good to you (tags has a little less flexibility in analytics / lead view versus custom fields).

**Comment by alexpelletier** [comment]
that sounds fine for now. 
They will want to know Lead/Inquiry type:
- by Lab 
- by Lab, by objective
- by expertise area

This will be important on the Lead page in Nutshell and also for reporting. So if custom field gets us there, let's do that then.
@lukad03 can you update the inquiry form to include this?

**Comment by lukad03** [comment]
@alexpelletier Adam needs to set up the input in Nutshell first. When he gets back we'll work on it together.

**Comment by lukad03** [comment]
Added
