### ISSUE TITLE
Lab accounts- and assigning

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#47]
Adam- is it one lab person per account? I assume yes, but we have two brookhaven people in our 'working group' so checking with you before pushing them to pick one person per lab account with nutshell. This is unless you've found another way to auto assign and trigger email notification of new inquiry assignment to lab?

**Comment by adamsfallen** [comment]
Okay several questions here:
1. Technically we may be able to create multiple users per account but it would take a little bit of extra effort and complicate our paradigm a bit (which I'd love to avoid). It would be much easier to just have one user / account for the time-being and users can just share a login like you suggested, unless there's some super compelling reason not to.
2. We can auto-assign inquiries to have whatever lab we like (based on, for example, what capabilities they're interested in). However, ultimately, I believe that lead can only have one user as the assignee.
3. Assuming that's true, then it would mean that triggering emails that result from account assignment can only be done for the one account that the lead was assigned to. However, the email address associated with the account can perhaps be an address set up to forward to multiple other addresses, which might be a pretty simple workaround if these users were super interested in that.

P.S. I'll leave it to you to close this issue if/when you feel like I've answered your question.

**Comment by alexpelletier** [comment]
@lukad03 to flag

**Comment by alexpelletier** [comment]
@adamsfallen I need help from you and @lukad03 to test how all three inquiry forms enter as pending, then when opened, are assigned and the corresponding notifications. I will test too- but more eyes on this particular process, the better. It is unclear to me.
