### ISSUE TITLE
Partner with a Lab- Require "Lab" field selected

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#49]

**Comment by alexpelletier** [comment]
It looks like the following fields are not required, but should be:
1. Lab selection
2. Organization (since nutshell uses this for header in Leads)

**Comment by lukad03** [comment]
Labs don't need to be required since there is a default option. So even if the field is skipped, a lab is still submitted.

https://github.com/presidential-innovation-fellows/ceic-partnering/pull/54
