### ISSUE TITLE
Assignment of Open (qualified) Inquiries by Lab

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#5]

**Comment by adamsfallen** [comment]
Sorry can you be more specific here? What are you looking for exactly?

**Comment by alexpelletier** [comment]
When an "Inquiry" comes in that is not auto-routed and is in "Open" pool (after qualified as not Spam) and assigned to a Lab, can there be a display of "Open- qualified" list of inquiries by Lab. This relates to the issue I just logged with the inquiry table for nutshell to include a Lab column.

**Comment by adamsfallen** [comment]
Ahh I think I understand and yes that is already currently supported, assuming we keep the "lab" / "requested lab" custom field.
