### ISSUE TITLE
Auto-email for "Partner with a Lab"

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#50]
I received the notification once I moved from Open-Pending and assigned NREL (which my account is associated)
<img width="780" alt="screen shot 2016-02-23 at 1 30 57 pm" src="https://cloud.githubusercontent.com/assets/14278320/13262140/691aac5a-da31-11e5-91cb-b93ed5f61f82.png">
-Inquiry: Fn/Ln
- can you change the language from "changed the is pending from 1 to 0" to "changed the status from Pending to Open"
- Inquiry type with Lab requested (from inquiry/source field)
- Objective when we have that.

Recent changes:
National Renewable Energy Lab changed the is pending from 1 to 0
Feb 23
12:27 PM
Partner
Wufoo form submission from IP: 159.142.0.109
×
Wufoo form submission from IP: 159.142.0.109
Today
Partner opened the lead

**Comment by adambellow** [comment]
Hey Alex,

Think this was for the other Adam.

A

--
Adam Bellow
Presidential Innovation Fellow
c: 202-215-2919
@adambellow
www.pif.gov

On Feb 24, 2016, at 4:11 PM, Alexandra Pelletier <notifications@github.com>
wrote:

Assigned #50
<https://github.com/presidential-innovation-fellows/ceic-partnering/issues/50>
to @adambellow <https://github.com/adambellow>.

—
Reply to this email directly or view it on GitHub
<https://github.com/presidential-innovation-fellows/ceic-partnering/issues/50#event-564450968>
.

**Comment by adamsfallen** [comment]
@alexpelletier to test.
