### ISSUE TITLE
Rename Sales Process and check box names

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#6]

**Comment by adamsfallen** [comment]
We can rename the milestones and activities to whatever, or limit them so there's only 1-2 for example. What would you like to rename them to?

**Comment by alexpelletier** [comment]
see issue #9

**Comment by adamsfallen** [comment]
FYI can support one step processes but need a process (e.g. Milestone = Contact and Activity = Contact Made).
