### ISSUE TITLE
Support "IsPending" status for all inquiries

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#7]

**Comment by alexpelletier** [comment]
Pending= All inquiries that come in 
Open= qualified (so not Cancelled/Spam) - how do we handle "auto routed" pending? they might be spam too.
<img width="343" alt="screen shot 2016-02-16 at 10 11 22 am" src="https://cloud.githubusercontent.com/assets/14278320/13080084/3260c556-d495-11e5-8b01-27ebb8cafc5f.png">

**Comment by adamsfallen** [comment]
@alexpelletier routing will simply add an assignee, not change the status of the inquiry. so for example, you could look in either the pending or open statuses and see a bunch of assignee that the system makes. does that make sense in your view?

**Comment by adamsfallen** [comment]
Supported

**Comment by alexpelletier** [comment]
so when inquiry comes in, all goes to Pending. If auto-assigned, then will be auto-assigned, but in Pending. All inquiries will also be shown in Open? so all pending and all open?

**Comment by adamsfallen** [comment]
No - inquiries can only be open or pending. Those are two separate stages.

**Comment by adamsfallen** [comment]
@alexpelletier any additional thoughts here or can I close?

**Comment by alexpelletier** [comment]
so it looks like all inquiries now come in as pending. When I change to "Open" the new behavior is:
Sales Process then populates on the form and is brought to the top of the page. I think it should move back below the "heading info" where you have custom fields. 
<img width="704" alt="screen shot 2016-02-22 at 4 24 34 pm" src="https://cloud.githubusercontent.com/assets/14278320/13233175/710ad856-d980-11e5-858c-7bd351d13b13.png">
