### ISSUE TITLE
Hide Tasks, Hide Sales Process

### ISSUE THREAD

**Issue by alexpelletier** [presidential-innovation-fellows/ceic-partnering#9]

**Comment by adambellow** [comment]
huh? Is this for @adamsfallen ?

**Comment by alexpelletier** [comment]
@adamsfallen IF we can't HIDE, then we will rename the "Sales Process" Github #6

**Comment by adamsfallen** [comment]
We need some kind of process even if it's one step (e.g. Milestone = Contact and Activity = Contact Made).

**Comment by adamsfallen** [comment]
I'm closing this because #6 is more relevant.
